operation:
  type: "Dir"  # Operation mode: "Pair" for pairwise or "Dir" for directory processing
  source_image: "DataWang/1/"  # Path to the source image
  target_image: ""  # Path to the target image (if type is Pair)
  output_folder: "NewOutputs/wang/"  # Path to the folder where results will be saved

image_processing:
  color_scale: "RGB"  # Color scale: "RGB" or "Gray"
  detector_type: "AKAZE"  # Feature detector type: "SIFT", "AKAZE", "SUPER"
  detector_threshold: 0.0001  # Threshold value for the detector
  max_keypoints: 2048  # Maximum number of keypoints (specific to some detectors like SUPER)

registration:
  global: false # Register Globally
  retry_numbers: 10 # Number of retries if Global Registration failed
  fine: true # Register with clusters
  max_clusters: 24 # Maximum Numebr of clusters
  num_clusters: 'auto'  # Number of clusters: "auto" or a specific number
  valid_range_weight: 0.2
matching:
  matcher_type: "Hamming"  # Matcher algorithm: "L2", "Hamming", "Light"
  
output_settings:
  save_results: true  # Whether to save the output results
  show_results: false  # Whether to display the output results
  apply_fix: false  # Whether to apply a fixing step to the outputs
